import type { Economy } from "./types";

const names = [
  ["afg", "Afghanistan", "AF", "AFG", "Asia-Pacific", "South and South-West Asia", ["Dari", "Pashto"]],
  ["alb", "Albania", "AL", "ALB", "Europe", "South-Eastern Europe", ["Albanian"]],
  ["arg", "Argentina", "AR", "ARG", "Latin America and Caribbean", "South America", ["Spanish"]],
  ["arm", "Armenia", "AM", "ARM", "Asia-Pacific", "North and Central Asia", ["Armenian"]],
  ["aus", "Australia", "AU", "AUS", "Asia-Pacific", "Pacific", ["English"]],
  ["aze", "Azerbaijan", "AZ", "AZE", "Asia-Pacific", "North and Central Asia", ["Azerbaijani"]],
  ["bgd", "Bangladesh", "BD", "BGD", "Asia-Pacific", "South and South-West Asia", ["Bengali", "English"]],
  ["brb", "Barbados", "BB", "BRB", "Latin America and Caribbean", "Caribbean", ["English"]],
  ["btn", "Bhutan", "BT", "BTN", "Asia-Pacific", "South and South-West Asia", ["Dzongkha", "English"]],
  ["bol", "Bolivia", "BO", "BOL", "Latin America and Caribbean", "South America", ["Spanish"]],
  ["bra", "Brazil", "BR", "BRA", "Latin America and Caribbean", "South America", ["Portuguese"]],
  ["brn", "Brunei Darussalam", "BN", "BRN", "Asia-Pacific", "South-East Asia", ["Malay", "English"]],
  ["khm", "Cambodia", "KH", "KHM", "Asia-Pacific", "South-East Asia", ["Khmer", "English"]],
  ["chl", "Chile", "CL", "CHL", "Latin America and Caribbean", "South America", ["Spanish"]],
  ["chn", "China", "CN", "CHN", "Asia-Pacific", "East and North-East Asia", ["Chinese"]],
  ["col", "Colombia", "CO", "COL", "Latin America and Caribbean", "South America", ["Spanish"]],
  ["cri", "Costa Rica", "CR", "CRI", "Latin America and Caribbean", "Central America", ["Spanish"]],
  ["cub", "Cuba", "CU", "CUB", "Latin America and Caribbean", "Caribbean", ["Spanish"]],
  ["dom", "Dominican Republic", "DO", "DOM", "Latin America and Caribbean", "Caribbean", ["Spanish"]],
  ["ecu", "Ecuador", "EC", "ECU", "Latin America and Caribbean", "South America", ["Spanish"]],
  ["slv", "El Salvador", "SV", "SLV", "Latin America and Caribbean", "Central America", ["Spanish"]],
  ["fji", "Fiji", "FJ", "FJI", "Asia-Pacific", "Pacific", ["English", "Fijian"]],
  ["geo", "Georgia", "GE", "GEO", "Asia-Pacific", "North and Central Asia", ["Georgian"]],
  ["gtm", "Guatemala", "GT", "GTM", "Latin America and Caribbean", "Central America", ["Spanish"]],
  ["guy", "Guyana", "GY", "GUY", "Latin America and Caribbean", "South America", ["English"]],
  ["hnd", "Honduras", "HN", "HND", "Latin America and Caribbean", "Central America", ["Spanish"]],
  ["hkg", "Hong Kong, China", "HK", "HKG", "Asia-Pacific", "East and North-East Asia", ["Chinese", "English"]],
  ["ind", "India", "IN", "IND", "Asia-Pacific", "South and South-West Asia", ["Hindi", "English"]],
  ["idn", "Indonesia", "ID", "IDN", "Asia-Pacific", "South-East Asia", ["Indonesian", "English"]],
  ["irn", "Iran", "IR", "IRN", "Asia-Pacific", "South and South-West Asia", ["Persian"]],
  ["jam", "Jamaica", "JM", "JAM", "Latin America and Caribbean", "Caribbean", ["English"]],
  ["jpn", "Japan", "JP", "JPN", "Asia-Pacific", "East and North-East Asia", ["Japanese"]],
  ["kaz", "Kazakhstan", "KZ", "KAZ", "Asia-Pacific", "North and Central Asia", ["Kazakh", "Russian"]],
  ["kir", "Kiribati", "KI", "KIR", "Asia-Pacific", "Pacific", ["English"]],
  ["kgz", "Kyrgyzstan", "KG", "KGZ", "Asia-Pacific", "North and Central Asia", ["Kyrgyz", "Russian"]],
  ["lao", "Lao PDR", "LA", "LAO", "Asia-Pacific", "South-East Asia", ["Lao"]],
  ["mys", "Malaysia", "MY", "MYS", "Asia-Pacific", "South-East Asia", ["Malay", "English"]],
  ["mdv", "Maldives", "MV", "MDV", "Asia-Pacific", "South and South-West Asia", ["Dhivehi", "English"]],
  ["mhl", "Marshall Islands", "MH", "MHL", "Asia-Pacific", "Pacific", ["English"]],
  ["mex", "Mexico", "MX", "MEX", "Latin America and Caribbean", "Central America", ["Spanish"]],
  ["fsm", "Micronesia", "FM", "FSM", "Asia-Pacific", "Pacific", ["English"]],
  ["mng", "Mongolia", "MN", "MNG", "Asia-Pacific", "East and North-East Asia", ["Mongolian"]],
  ["mmr", "Myanmar", "MM", "MMR", "Asia-Pacific", "South-East Asia", ["Burmese"]],
  ["npl", "Nepal", "NP", "NPL", "Asia-Pacific", "South and South-West Asia", ["Nepali", "English"]],
  ["nzl", "New Zealand", "NZ", "NZL", "Asia-Pacific", "Pacific", ["English", "Maori"]],
  ["nic", "Nicaragua", "NI", "NIC", "Latin America and Caribbean", "Central America", ["Spanish"]],
  ["pak", "Pakistan", "PK", "PAK", "Asia-Pacific", "South and South-West Asia", ["Urdu", "English"]],
  ["plw", "Palau", "PW", "PLW", "Asia-Pacific", "Pacific", ["English", "Palauan"]],
  ["pan", "Panama", "PA", "PAN", "Latin America and Caribbean", "Central America", ["Spanish"]],
  ["png", "Papua New Guinea", "PG", "PNG", "Asia-Pacific", "Pacific", ["English"]],
  ["pry", "Paraguay", "PY", "PRY", "Latin America and Caribbean", "South America", ["Spanish", "Guarani"]],
  ["per", "Peru", "PE", "PER", "Latin America and Caribbean", "South America", ["Spanish"]],
  ["phl", "Philippines", "PH", "PHL", "Asia-Pacific", "South-East Asia", ["Filipino", "English"]],
  ["kor", "Republic of Korea", "KR", "KOR", "Asia-Pacific", "East and North-East Asia", ["Korean"]],
  ["rus", "Russian Federation", "RU", "RUS", "Asia-Pacific", "North and Central Asia", ["Russian"]],
  ["wsm", "Samoa", "WS", "WSM", "Asia-Pacific", "Pacific", ["Samoan", "English"]],
  ["sgp", "Singapore", "SG", "SGP", "Asia-Pacific", "South-East Asia", ["English", "Malay", "Chinese", "Tamil"]],
  ["slb", "Solomon Islands", "SB", "SLB", "Asia-Pacific", "Pacific", ["English"]],
  ["lka", "Sri Lanka", "LK", "LKA", "Asia-Pacific", "South and South-West Asia", ["Sinhala", "Tamil", "English"]],
  ["sur", "Suriname", "SR", "SUR", "Latin America and Caribbean", "South America", ["Dutch"]],
  ["tjk", "Tajikistan", "TJ", "TJK", "Asia-Pacific", "North and Central Asia", ["Tajik", "Russian"]],
  ["tha", "Thailand", "TH", "THA", "Asia-Pacific", "South-East Asia", ["Thai", "English"]],
  ["tls", "Timor-Leste", "TL", "TLS", "Asia-Pacific", "South-East Asia", ["Tetum", "Portuguese"]],
  ["ton", "Tonga", "TO", "TON", "Asia-Pacific", "Pacific", ["Tongan", "English"]],
  ["tto", "Trinidad and Tobago", "TT", "TTO", "Latin America and Caribbean", "Caribbean", ["English"]],
  ["tur", "Turkiye", "TR", "TUR", "Asia-Pacific", "North and Central Asia", ["Turkish"]],
  ["tkm", "Turkmenistan", "TM", "TKM", "Asia-Pacific", "North and Central Asia", ["Turkmen", "Russian"]],
  ["tuv", "Tuvalu", "TV", "TUV", "Asia-Pacific", "Pacific", ["English", "Tuvaluan"]],
  ["ury", "Uruguay", "UY", "URY", "Latin America and Caribbean", "South America", ["Spanish"]],
  ["uzb", "Uzbekistan", "UZ", "UZB", "Asia-Pacific", "North and Central Asia", ["Uzbek", "Russian"]],
  ["vut", "Vanuatu", "VU", "VUT", "Asia-Pacific", "Pacific", ["Bislama", "English", "French"]],
  ["ven", "Venezuela", "VE", "VEN", "Latin America and Caribbean", "South America", ["Spanish"]],
  ["vnm", "Viet Nam", "VN", "VNM", "Asia-Pacific", "South-East Asia", ["Vietnamese", "English"]],
  ["dza", "Algeria", "DZ", "DZA", "Africa", "Northern Africa", ["Arabic", "French"]],
  ["ago", "Angola", "AO", "AGO", "Africa", "Middle Africa", ["Portuguese"]],
  ["ben", "Benin", "BJ", "BEN", "Africa", "Western Africa", ["French"]],
  ["bwa", "Botswana", "BW", "BWA", "Africa", "Southern Africa", ["English", "Tswana"]],
  ["bfa", "Burkina Faso", "BF", "BFA", "Africa", "Western Africa", ["French"]],
  ["cmr", "Cameroon", "CM", "CMR", "Africa", "Middle Africa", ["English", "French"]],
  ["civ", "Cote d'Ivoire", "CI", "CIV", "Africa", "Western Africa", ["French"]],
  ["egy", "Egypt", "EG", "EGY", "Africa", "Northern Africa", ["Arabic", "English"]],
  ["eth", "Ethiopia", "ET", "ETH", "Africa", "Eastern Africa", ["Amharic", "English"]],
  ["gha", "Ghana", "GH", "GHA", "Africa", "Western Africa", ["English"]],
  ["ken", "Kenya", "KE", "KEN", "Africa", "Eastern Africa", ["English", "Swahili"]],
  ["mar", "Morocco", "MA", "MAR", "Africa", "Northern Africa", ["Arabic", "French"]],
  ["moz", "Mozambique", "MZ", "MOZ", "Africa", "Eastern Africa", ["Portuguese"]],
  ["nga", "Nigeria", "NG", "NGA", "Africa", "Western Africa", ["English"]],
  ["rwa", "Rwanda", "RW", "RWA", "Africa", "Eastern Africa", ["Kinyarwanda", "English", "French"]],
  ["sen", "Senegal", "SN", "SEN", "Africa", "Western Africa", ["French"]],
  ["zaf", "South Africa", "ZA", "ZAF", "Africa", "Southern Africa", ["English"]],
  ["tza", "United Republic of Tanzania", "TZ", "TZA", "Africa", "Eastern Africa", ["Swahili", "English"]],
  ["tun", "Tunisia", "TN", "TUN", "Africa", "Northern Africa", ["Arabic", "French"]],
  ["uga", "Uganda", "UG", "UGA", "Africa", "Eastern Africa", ["English", "Swahili"]],
  ["zmb", "Zambia", "ZM", "ZMB", "Africa", "Eastern Africa", ["English"]],
  ["zwe", "Zimbabwe", "ZW", "ZWE", "Africa", "Eastern Africa", ["English"]],
  ["bhr", "Bahrain", "BH", "BHR", "Western Asia", "Gulf", ["Arabic", "English"]],
  ["jor", "Jordan", "JO", "JOR", "Western Asia", "Levant", ["Arabic", "English"]],
  ["kwt", "Kuwait", "KW", "KWT", "Western Asia", "Gulf", ["Arabic", "English"]],
  ["omn", "Oman", "OM", "OMN", "Western Asia", "Gulf", ["Arabic", "English"]],
  ["qat", "Qatar", "QA", "QAT", "Western Asia", "Gulf", ["Arabic", "English"]],
  ["sau", "Saudi Arabia", "SA", "SAU", "Western Asia", "Gulf", ["Arabic", "English"]],
  ["are", "United Arab Emirates", "AE", "ARE", "Western Asia", "Gulf", ["Arabic", "English"]],
  ["ukr", "Ukraine", "UA", "UKR", "Europe", "Eastern Europe", ["Ukrainian"]],
] as const;

export const economiesSeed: Omit<Economy, "createdAt">[] = names.slice(0, 102).map(([id, name, iso2, iso3, region, subregion, languages]) => ({
  id,
  name,
  iso2,
  iso3,
  region,
  subregion,
  languages: [...languages],
}));
